apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem 
  # volumeMode: Block 
  storageClassName: standard
  accessModes:
    # - type and how many nodes can claim
    - ReadWriteOnce # Read Write access -> One node (but multiple PODs)

    # - ReadWriteMany # Read Write access -> Multiple nodes
    # - ReadOnlyMany # Not available for hostPath
  hostPath:
    path: /data
    type: DirectoryOrCreate
