apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: user
          image: terminalwarlord/kub-demo-user:latest
          env:
            - name: AUTH_ADDRESS
              value: localhost
        - name: auth
          image: terminalwarlord/kub-demo-auth:latest